### PR TITLE
add api invite manager configs

### PR DESCRIPTION
**Pull request by mrvahedi68**

### CODE REVIEW

**Comment by MahdiBaghbani** [comment]
what about revad and revaoc configs?

**Comment by mrvahedi68** [comment]
We have this functionality for Nextcloud currently.

**Comment by MahdiBaghbani** [comment]
So you work on this branch. Do you need to merge it right now? or we wait until everything is ready?

**Comment by MahdiBaghbani** [comment]
Since the Reva has changed into 3 process configuration, we might need to change this.

**Comment by michielbdejong** [comment]
This has been superseded by other changes

**Pull request closed without merging**
